name: Deploy Frontend Client to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Frontend to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '3.136.200.153'
        username: 'ec2-user'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: '22'
        script: |
          # Navigate to client directory and update code
          cd ~/client
          git pull origin main
          
          # Navigate to docker-compose directory
          cd ~/docker-compose
          
          # Rebuild and restart the frontend container
          docker-compose -f dockercompose.yml stop frontend-client
          docker-compose -f dockercompose.yml build client
          docker-compose -f dockercompose.yml up -d client