name: Deploy Frontend Client to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Connect to EC2 instance
      run: |

        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/deploy_key
        chmod 600 ~/deploy_key
        ssh -i "~/deploy_key" ec2-user@3.136.200.153 "
          cd downloads
          cd client 
          git pull origin main
          cd ..
          docker-compose -f dockercompose.yml down
          docker system prune -a -f
          docker-compose -f dockercompose.yml build
          docker-compose -f dockercompose.yml up -d
        "