name: Deploy Frontend Client to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H 3.136.200.153 >> ~/.ssh/known_hosts

    - name: Deploy Frontend to EC2
      run: |
        ssh -i ~/.ssh/deploy_key ec2-user@3.136.200.153 '
          # Navigate to client directory and update code
          cd ~/client
          git pull origin main
          
          # Navigate to docker-compose directory
          cd ~/docker-compose
          
          # Rebuild and restart the frontend container
          docker-compose -f dockercompose.yml stop frontend-client
          docker-compose -f dockercompose.yml build client
          docker-compose -f dockercompose.yml up -d client
        '